### ISSUE TITLE
final analysis blog edits

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ojd-daps-skills-analysis#5]
- [x] update copy
- [ ] make axes darker (if possible)
- [ ] move extracted skills image not next to each other so the image is larger and font is bigger

**Comment by india-kerle** [comment]
fyi @lizgzil based on sanjiv's comments

**Comment by lizgzil** [comment]
@india-kerle I like the extracted skills side by side - think it makes it clear! 
Not sure how possible it is - but a way to make the text bigger would be to take the screen grab when you've narrowed the window a bit?, so the image isn't as wide but is longer.

I don't have the text from the job advert you put in, so can't do it - do you still have it?

**Comment by india-kerle** [comment]
@lizgzil annoyingly I don't! But the GIF needs updating anyways so i'll just find a new software engineer role and save that copy
